[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"

[[bin]]
name = "d1"
path = "d1/main.rs"

[[bin]]
name = "d2"
path = "d2/main.rs"

[[bin]]
name = "d3"
path = "d3/main.rs"


[[bin]]
name = "d4"
path = "d4/main.rs"